%WM = bspwm
%TERMINAL = alacritty
%FILEMGR = thunar
%BROWSER = firefox
%LOCATION = N45_416S20_198
%MAILCLIENT = 

[init]
wm/bspwm
hid/keyboard,sxhkd
screen/layout(defined,'Default')
ui/polybar,picom
services/apps
ui/battery

[reload]
wm/bspwm(workspaces)
hid/sxhkd(reload)
ui/polybar(restart)
