Section "Monitor"
    Identifier "DisplayPort-0" 
    Modeline   "1920x1080_140.00"  438.75  1920 2088 2296 2672  1080 1083 1088 1174
    Option     "PreferredMode" "1920x1080"
    Option     "TargetRefresh" "140"
EndSection
Section "Monitor"
    Identifier "HDMI-A-0" 
    Option     "PreferredMode" "1920x1080"
    Option     "TargetRefresh" "60"
    Option     "RightOf" "DisplayPort-0"
EndSection
