## This is just an example config file.
## Please edit the paths and kernel parameters according to your system.

title   Arch Linux
linux   /vmlinuz-linux-zen
initrd  /intel-ucode.img
initrd  /initramfs-linux-zen.img
options root=PARTUUID=127c594a-3c9b-0b46-9b54-9cc75a820fe6 rw loglevel=3 quiet add_efi_memmap
