#! /usr/bin/env dash

wmrc &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & eval $(gnome-keyring-daemon -s --components=pkcs11,secrets,ssh,gpg) &

nitrogen --restore &

/usr/lib/kdeconnectd &

xfce4-clipman &

flameshot &

pnmixer &

mictray &

nm-applet --indicator &

xfce4-power-manager &

ckb-next &

steam -silent &

discord-canary &
